### ISSUE TITLE
Error when passing Image path

### ISSUE THREAD

**Issue by vyraun** [jacobgil/keras-cam#1]
Hi

When I tried the model by passing an image path I got:

Using Theano backend.
Traceback (most recent call last):
  File "cam.py", line 62, in <module>
    visualize_class_activation_map(args.model_path, args.image_path, args.output_path)
  File "cam.py", line 18, in visualize_class_activation_map
    model = load_model(model_path)
  File "/home/vyraun/anaconda2/lib/python2.7/site-packages/keras/models.py", line 121, in load_model
    f = h5py.File(filepath, mode='r')
  File "/home/vyraun/anaconda2/lib/python2.7/site-packages/h5py/_hl/files.py", line 267, in __init__
    name = name.encode(sys.getfilesystemencoding())
AttributeError: 'NoneType' object has no attribute 'encode'

I guess I am not passing the parameter correctly.

**Comment by jacobgil** [comment]
Hi,
A checkpoint with the model weights should be passed with --model_path.
To get a checkpoint you can either first train it yourself by passing --train,
or use the checkpoint I trained and now uploaded to google drive:
https://drive.google.com/open?id=0B1l5JSkBbENBdk95ZW1DOUhqQUE
Pass --model_path cam_checkpoint.hdf5
Will add it to the README.
