### ISSUE TITLE
Error in model construction

### ISSUE THREAD

**Issue by OptimusCrime** [jacobgil/keras-cam#3]
Trying to train the network results in the following error:

```
Traceback (most recent call last):
  File "cam.py", line 60, in <module>
    train(args.dataset_path)
  File "cam.py", line 11, in train
    model = get_model()
  File "~/master/code/keras-cam-master/model.py", line 53, in get_model
    model = VGG16_convolutions()
  File "~/master/code/keras-cam-master/model.py", line 17, in VGG16_convolutions
    model.add(Convolution2D(64, 3, 3, activation='relu', name='conv1_1'))
  File "/Users/username/.virtualenvs/keraspython2/lib/python2.7/site-packages/keras/models.py", line 312, in add
    output_tensor = layer(self.outputs[0])
  File "/Users/username/.virtualenvs/keraspython2/lib/python2.7/site-packages/keras/engine/topology.py", line 487, in __call__
    self.build(input_shapes[0])
  File "/Users/username/.virtualenvs/keraspython2/lib/python2.7/site-packages/keras/layers/convolutional.py", line 410, in build
    self.W = self.init(self.W_shape, name='{}_W'.format(self.name))
  File "/Users/username/.virtualenvs/keraspython2/lib/python2.7/site-packages/keras/initializations.py", line 57, in glorot_uniform
    fan_in, fan_out = get_fans(shape, dim_ordering=dim_ordering)
  File "/Users/username/.virtualenvs/keraspython2/lib/python2.7/site-packages/keras/initializations.py", line 15, in get_fans
    receptive_field_size = np.prod(shape[2:])
  File "/Users/username/.virtualenvs/keraspython2/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2539, in prod
    out=out, **kwargs)
  File "/Users/username/.virtualenvs/keraspython2/lib/python2.7/site-packages/numpy/core/_methods.py", line 35, in _prod
    return umr_prod(a, axis, dtype, out, keepdims)
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```

Running version `Keras==1.1.1`

**Comment by jacobgil** [comment]
Is the backend Tensorflow or Theano?
Can be checked in ~/.keras/keras.json

**Comment by OptimusCrime** [comment]
Identical error with either backend. This is running Tensorflow. 

pip packages:

```
funcsigs==1.0.2
h5py==2.6.0
Keras==1.1.1
mock==2.0.0
numpy==1.11.2
pbr==1.10.0
protobuf==3.0.0
PyYAML==3.12
scipy==0.18.1
six==1.10.0
stevedore==1.17.1
tensorflow==0.11.0rc2
virtualenv==15.0.3
virtualenv-clone==0.2.6
virtualenvwrapper==4.7.2
```

**Comment by jacobgil** [comment]
Thanks for the issue.
The model assumes theano dimension ordering.
Please change image_dim_ordering to th.
keras.json should look similar to this:
{
    "image_dim_ordering": "th", 
    "epsilon": 1e-07, 
    "floatx": "float32", 
    "backend": "theano"
}

I will add this to the readme.

Actually it's probably best to use the VGG16 supplied in keras.applications, since it has default support for both tensorflow and theano.

**Comment by jacobgil** [comment]
An example of that can be found in https://github.com/jacobgil/keras-grad-cam,
which I would recommend, since then you can play with class activation maps on pre-trained VGG16 without retraining.

**Comment by OptimusCrime** [comment]
Thank you so much! However, it is not crashing because I do not have a h5 file. How are you supposed to call the script when training (building) the network with weights? As far as I can tell from the code, it will always attempt to load the model from file at line https://github.com/jacobgil/keras-cam/blob/master/model.py#L54

I am running with

```
python cam.py --train=True --dataset_path=~/Downloads/INRIAPerson/train_64x128_H96
```

**Comment by jacobgil** [comment]
Yes that is a bug.
I pushed a fix (not loading weights when training).
Can you please confirm this works?

**Comment by OptimusCrime** [comment]
Thank you so much. I made it work with just commenting out the line. I'll pull your updated code later. Thank you for much help. I am looking at your code for some guidance for solving a similar problem for my master thesis. You just made one student very happy.

**Comment by jacobgil** [comment]
The VGG16 weights can be taken from here:
https://github.com/awentzonline/keras-vgg-buddy 
https://github.com/awentzonline/keras-vgg-buddy/releases/download/0.0.1/vgg16_weights.h5

These weights should be loaded, since the training only trains the new "GAP" layer on top of the VGG16 conv layers.

**Comment by jacobgil** [comment]
Btw I made an incorrect fix and then reverted it, so please do a git pull .
